version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: elder-care-flask-app:1.0
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_CONFIG=${FLASK_CONFIG}
      - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      - ELDERS_DATA_DIR=${ELDERS_DATA_DIR}
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    command: python -u run.py
    restart: unless-stopped
    user: "${UID}:${GID}"